### ISSUE TITLE
Embark timeout?

### ISSUE THREAD

**Issue by onyxraven** [Lachee/fivem-busdriver#3]
Hi there!

You've got in the README a note about the embark timeout. I do see that you are [checking the time here](https://github.com/Lachee/fivem-busdriver/blob/master/client/entities/Job.lua#L257)  - but the [config has the default at 15000 ](https://github.com/Lachee/fivem-busdriver/blob/master/config.lua#L25) - it looks like that [might actually be seconds though](https://github.com/Lachee/fivem-busdriver/blob/master/common/entities/Stopwatch.lua#L30)? that'd be a lot of seconds! 

Happy to put in a PR once I check this out on my server.

**Comment by Lachee** [comment]
huh, at https://github.com/Lachee/fivem-busdriver/blob/a1198c5a1bba80c816b985e3c998aa0f5123d942/common/entities/Stopwatch.lua#L30 it looks like you are correct, it is in seconds.
If you can submit a PR that would be awesome. Love seeing people use this job ❤
